/**
 * Header file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer12/CPP1.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { 

class Producer12 : public Sequential
{

public:
  // Define constructor and destructor
  Producer12(ChannelIn<int> *ch1, ChannelIn<int> *ch2);
  virtual ~Producer12();

private:

  // Class variables
  int anotherValue;
  int someValue;

  // Model objects
  CPP1::CPP1 *myCPP1;
  Writer<int> *myP12_W_ch1;
  Writer<int> *myP12_W_ch2;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
