/**
 * Source file for the CPP22 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer122/CPP22.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer122 { namespace CPP22 { 

CPP22::CPP22(int &aVariable, int &bVariable) :
    CodeBlock(), aVariable(aVariable), bVariable(bVariable){
  SETNAME(this, "CPP22");

  // protected region constructor on begin
  // protected region constructor end
}

CPP22::~CPP22()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP22::execute()
{
  // protected region execute code on begin
		printf("CPP22 read aVariable as %d \n",aVariable);
		printf("CPP22 read bVariable as %d \n",bVariable);
	  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
