/**
 * Header file for the CPPout2 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer2 { namespace CPPout2 { 

class CPPout2 : public CodeBlock
{

public:
  // Define constructor and destructor
  CPPout2();
  virtual ~CPPout2();

  void execute();

private:
  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
