# build.mk file for model.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/model

model/model:
	@echo
	@echo "Building $@"
	@make -C model --no-print-directory

bin/model: model/model | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/model gets properly rebuild
model/model: model/src/main.cpp
model/model: model/src/MainModel.cpp model/include/MainModel.h
model/model: model/src/Producer.cpp model/include/Producer.h
model/model: model/src/Producer/CPPin.cpp model/include/Producer/CPPin.h
model/model: model/src/Consumer1.cpp model/include/Consumer1.h
model/model: model/src/Consumer1/CPPout1.cpp model/include/Consumer1/CPPout1.h
model/model: model/src/Consumer2.cpp model/include/Consumer2.h
model/model: model/src/Consumer2/CPPout2.cpp model/include/Consumer2/CPPout2.h
model/model: model/src/Consumer3.cpp model/include/Consumer3.h
model/model: model/src/Consumer3/CPPout3.cpp model/include/Consumer3/CPPout3.h

# protected region additional dependencies on begin
# protected region additional dependencies end