/**
 * Header file for the Consumer122 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer122/CPP22.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer122 { 

class Consumer122 : public Sequential
{

public:
  // Define constructor and destructor
  Consumer122(ChannelOut<int> *ch12, ChannelOut<int> *ch22);
  virtual ~Consumer122();

private:

  // Class variables
  int aVariable;
  int bVariable;

  // Model objects
  Reader<int> *myC122_R_ch12;
  Reader<int> *myC122_R_ch22;
  CPP22::CPP22 *myCPP22;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
