/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer12.h"
#include "Consumer122.h"
#include "Producer12.h"
#include "Producer122.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Parallel
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myProducer122ch12_to_Consumer122ch12Channel;
  UnbufferedChannel<int, One2In, Out2One> *myProducer122ch22_to_Consumer122ch22Channel;
  UnbufferedChannel<int, One2In, Out2One> *myProducer12ch1_to_Consumer12ch1Channel;
  UnbufferedChannel<int, One2In, Out2One> *myProducer12ch2_to_Consumer12ch2Channel;

  // Model objects
  Consumer12::Consumer12 *myConsumer12;
  Consumer122::Consumer122 *myConsumer122;
  Producer12::Producer12 *myProducer12;
  Producer122::Producer122 *myProducer122;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
