/**
 * Header file for the CPP1 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer122 { namespace CPP1 { 

class CPP1 : public CodeBlock
{

public:
  // Define constructor and destructor
  CPP1(int &anotherValue, int &someValue);
  virtual ~CPP1();

  void execute();

private:

  // Class variables
  int &anotherValue;
  int &someValue;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
