/**
 * Source file for the CPP2 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer12/CPP2.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer12 { namespace CPP2 { 

CPP2::CPP2(int &aVariable, int &bVariable) :
    CodeBlock(), aVariable(aVariable), bVariable(bVariable){
  SETNAME(this, "CPP2");

  // protected region constructor on begin
  // protected region constructor end
}

CPP2::~CPP2()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP2::execute()
{
  // protected region execute code on begin
	printf("CPP2 read aVariable as %d \n",aVariable);
	printf("CPP2 read bVariable as %d \n",bVariable);
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
