# build.mk file for SystemDF.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/SystemDF

SystemDF/SystemDF:
	@echo
	@echo "Building $@"
	@make -C SystemDF --no-print-directory

bin/SystemDF: SystemDF/SystemDF | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/SystemDF gets properly rebuild
SystemDF/SystemDF: SystemDF/src/main.cpp
SystemDF/SystemDF: SystemDF/src/MainModel.cpp SystemDF/include/MainModel.h
SystemDF/SystemDF: SystemDF/src/Producer12.cpp SystemDF/include/Producer12.h
SystemDF/SystemDF: SystemDF/src/Producer12/CPP1.cpp SystemDF/include/Producer12/CPP1.h
SystemDF/SystemDF: SystemDF/src/Consumer12.cpp SystemDF/include/Consumer12.h
SystemDF/SystemDF: SystemDF/src/Consumer12/CPP2.cpp SystemDF/include/Consumer12/CPP2.h
SystemDF/SystemDF: SystemDF/src/Producer122.cpp SystemDF/include/Producer122.h
SystemDF/SystemDF: SystemDF/src/Producer122/CPP12.cpp SystemDF/include/Producer122/CPP12.h
SystemDF/SystemDF: SystemDF/src/Consumer122.cpp SystemDF/include/Consumer122.h
SystemDF/SystemDF: SystemDF/src/Consumer122/CPP22.cpp SystemDF/include/Consumer122/CPP22.h

# protected region additional dependencies on begin
# protected region additional dependencies end