/**
 * Source file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer12 { 

Producer12::Producer12(ChannelIn<int> *ch1, ChannelIn<int> *ch2) :
    Sequential(NULL)
{
  SETNAME(this, "Producer12");

  // Initialize model objects
  myCPP1 = new CPP1::CPP1(anotherValue, someValue);
  SETNAME(myCPP1, "CPP1");
  myP12_W_ch1 = new Writer<int>(&someValue, ch1);
  SETNAME(myP12_W_ch1, "P12_W_ch1");
  myP12_W_ch2 = new Writer<int>(&anotherValue, ch2);
  SETNAME(myP12_W_ch2, "P12_W_ch2");


  // Register model objects
  this->append_child(myCPP1);
  this->append_child(myP12_W_ch1);
  this->append_child(myP12_W_ch2);

  // protected region constructor on begin
  // protected region constructor end
}

Producer12::~Producer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myP12_W_ch2;
  delete myP12_W_ch1;
  delete myCPP1;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
