/**
 * Header file for the Consumer2 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer2/CPPout2.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer2 { 

class Consumer2 : public Sequential
{

public:
  // Define constructor and destructor
  Consumer2(ChannelOut<bool> *C);
  virtual ~Consumer2();

private:

  // Class variables
  bool VarIn;

  // Model objects
  Reader<bool> *myC2_R_C;
  CPPout2::CPPout2 *myCPPout2;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
