/**
 * Header file for the Consumer3 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer3/CPPout3.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer3 { 

class Consumer3 : public Sequential
{

public:
  // Define constructor and destructor
  Consumer3(ChannelOut<int> *C);
  virtual ~Consumer3();

private:

  // Class variables
  int VarIn;

  // Model objects
  Reader<int> *myC3_R_C;
  CPPout3::CPPout3 *myCPPout3;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
