/**
 * Header file for the Producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer/CPPin.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer { 

class Producer : public Sequential
{

public:
  // Define constructor and destructor
  Producer(GuardedChannelIn<int> *C1, GuardedChannelIn<int> *C2, GuardedChannelIn<int> *C3);
  virtual ~Producer();

private:

  // Class variables
  int ChVar1;
  int ChVar2;
  int ChVar3;

  // Model objects
  CPPin::CPPin *myCPPin;
  GuardedWriter<int> *myP_W_C1;
  GuardedWriter<int> *myP_W_C2;
  GuardedWriter<int> *myP_W_C3;

  // Model groups
  Alternative *myALTERNATIVE;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
