/**
 * Header file for the Producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer/CPPin.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer { 

class Producer : public Sequential
{

public:
  // Define constructor and destructor
  Producer(GuardedChannelIn<bool> *C1, GuardedChannelIn<bool> *C2, GuardedChannelIn<bool> *C3);
  virtual ~Producer();

private:

  // Class variables
  bool ChVar1;
  bool ChVar2;
  bool ChVar3;

  // Model objects
  CPPin::CPPin *myCPPin;
  GuardedWriter<bool> *myP_W_C1;
  GuardedWriter<bool> *myP_W_C2;
  GuardedWriter<bool> *myP_W_C3;

  // Model groups
  Alternative *myALTERNATIVE;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
