/**
 * Source file for the Consumer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer12 { 

Consumer12::Consumer12(ChannelOut<int> *ch1, ChannelOut<int> *ch2) :
    Sequential(NULL)
{
  SETNAME(this, "Consumer12");

  // Initialize model objects
  myC12_R_ch1 = new Reader<int>(&aVariable, ch1);
  SETNAME(myC12_R_ch1, "C12_R_ch1");
  myC12_R_ch2 = new Reader<int>(&bVariable, ch2);
  SETNAME(myC12_R_ch2, "C12_R_ch2");
  myCPP2 = new CPP2::CPP2(aVariable, bVariable);
  SETNAME(myCPP2, "CPP2");


  // Register model objects
  this->append_child(myC12_R_ch1);
  this->append_child(myC12_R_ch2);
  this->append_child(myCPP2);

  // protected region constructor on begin
  // protected region constructor end
}

Consumer12::~Consumer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myCPP2;
  delete myC12_R_ch2;
  delete myC12_R_ch1;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
